### ISSUE TITLE
 SRV-I-9: checkClaimKeyBan()/deleteOld* doesn't work outside UTC

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-server#137]
**Analysis of the Issue**

During code review of ../covid-shield-server/blob/deploy_tf/pkg/persistence/queries.go#L346.

checkClaimKeyBan() gets the time of the last failure from the DB and subtracts it from the remaining ban duration. However, this only works if the local time is set to UTC.

The value is previously stored in the DB via mysql NOW(), which stores the time in local time. When it is read back, because the timestamp does not contain timezone info, q.Scan() assumes UTC. This causes the elapsed duration to be very large (if negative offset timezone), never causing a ban, or very negative (positive offset timezone), causing a much longer ban than expected.

I suspect other functions using stored timestamps behave similarly.

This behavior may be expected if setting clocks to UTC is a requirement of the running environment, but it's not documented anywhere.

**Recommendation**

Provide clarification on expected behaviour and requirement on setting clocks to UTC.

**Comment by CalvinRodo** [comment]
Working as expected, could not repro
