### ISSUE TITLE
Create necessary conditions to enable PrivateLink between covid-health-portal and OTC generation endpoint

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-server#178]
To further reduce the attack surface on the OTC endpoint, and to allow for a no-egress securitygroup on the health-portal subnet, create a PrivateLink between the two services.

**Comment by maxneuvians** [comment]
https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html

**Comment by obrien-j** [comment]
I was thinking more along the lines of https://aws.amazon.com/privatelink/

**Comment by maxneuvians** [comment]
You are correct - would be more appropriate

**Comment by maxneuvians** [comment]
PrivateLink does not seem to be compatible with our Blue/Green deploys
