### ISSUE TITLE
Feature flag the 'partial todays date', until it gets officially pushed into the api spec

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-server#184]
https://github.com/cds-snc/covid-shield-server/blob/0823b9417855fb4e281fe94af39d5c6471b74273/pkg/server/upload.go#L246

Close if this is not valid @maxneuvians but I believe this change was put in recently to accomodate the partial today uploads Google had pushed into the safelist testing.

**Comment by maxneuvians** [comment]
This issue is outdated as partial day keys are both in iOS and Android now
