### ISSUE TITLE
Reduce domain space from 2 to 1 to minimize traffic analysis concerns

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-server#185]
Given the lack of 'junk data' traffic flows being implemented in both the app/server side to reduce the ability of an attacker to infer diagnosed state of IP addresses via network traffic analysis, implement small mitigations where we can.

The way we use two domain names, retrieval and submission, exposes this somewhat trivially to any parties who have the ability to inspect DNS logs. Unless there's a specific reason (alb routing/waf/etc) we need the multiple domains, recommend reducing to a single domain.

**Comment by maxneuvians** [comment]
we can deploy the already existing monolith vs the two services

**Comment by stonith** [comment]
> we can deploy the already existing monolith vs the two services

We can also use path-based forwarding on a single ALB to achieve this assuming there are no paths between the two services that overlap. 

However, there's a tradeoff given that the retrieval service requires a CDN for distribution and consolidating the endpoint FQDN will also require submission service requests to pass through the AWS Cloudfront CDN as well. There is no control over which edge locations can be used and therefore some submission endpoint requests would pass through non-Canadian edge locations and logging data would also reside outside of Canada.

**Comment by maxneuvians** [comment]
Given that we can't ensure the routing of traffic solely through Canada for submission this seems unrealistic at this point in time, if this changes we can re-visit.
