### ISSUE TITLE
Implement a simpler update mechanism for dynamic configuration/app-content 

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/covid-alert-server#195]
Currently the `exposure-configuration.json` is being served from the server. We should validate that this the optimal place for it compared to, for example, an S3 bucket. This was a `TODO` recommendation from codebase.

**Comment by maxneuvians** [comment]
Would recommend putting it into GitHub

**Comment by Stephen-PM** [comment]
Why? This will allow us to make changes to the config file without having to re-deploy the server. This will also provides a mechanism for the provincial customizations to be moved to the config file, so that provinces can be onboarded or request content changes without a need to change the app.

**Comment by maxneuvians** [comment]
This is more or less closed, how we update the content of the S3 bucket is outside of the scope of the issue.
