### ISSUE TITLE
Base line traffic analysis and alerts

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/covid-alert-server#246]
Given that we have about a week of traffic data, we should start baselining our alerts to detect significant variances (ex. traffic drops 50%).

Risk: We could be alerted to frequently or not frequently enough because the alerts are not calibrated to reflect the current reality.

AC: 
- [ ] analyze traffic
- [ ] update alerts

**Comment by Stephen-PM** [comment]
This should be done periodically to refine alerts.

**Comment by maxneuvians** [comment]
We are more or less already doing this regularly
