### ISSUE TITLE
Replace or adopt Shopify Goose packages.

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/covid-alert-server#254]
The server was created using code from Shopify's Goose Package https://github.com/Shopify/goose

While the code works well the package is undocumented, and there is no guarantee that Shopify won't introduce breaking changes. 

We'd like to replace them with more well known and more popular libraries if needed. 

Items to replace 

- [ ] github.com/Shopify/goose/genmain
- [ ] github.com/Shopify/goose/srvutil
- [ ] github.com/Shopify/goose/profiler
- [ ] github.com/Shopify/goose/safely

Items to keep
- [ ] github.com/Shopify/goose/logger

**Comment by CalvinRodo** [comment]
Logger is a lightweight wrapper around [logrus](https://github.com/sirupsen/logrus) probably not worth replacing this one, I'd rather rely on a vendor'd copy or make it our own and document it a bit better.

**Comment by CalvinRodo** [comment]
We've decided to just fork this project so we can manage merges from upstream.

**Comment by Stephen-PM** [comment]
Putting on hold, questioning whether this is worth doing.
