### ISSUE TITLE
Device and Server Event Aggregation

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/covid-alert-server#265]
Add an event ingress to the server. 

Events should be aggregated into daily totals by device. 

The endpoint should also do device attestation to ensure that metrics are accurate.

**Comment by CalvinRodo** [comment]
We can use a similar method (minus device attestation) to aggregate server metrics, we can aggregate by PT instead of device type for daily totals.

**Comment by CalvinRodo** [comment]
This should reference an issue in github.com/cds-snc/covid-shield-mobile

**Comment by Stephen-PM** [comment]
Being tracking in #256
