### ISSUE TITLE
Enable DNS query logging inside VPC

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/covid-alert-server#284]
Once we start looking at features like device attestation which require egress, we should look at this new feature in AWS https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/monitoring-overview.html and set up an alert if queries are made against non-safelisted targets.

AC:
- [ ] Investigate the traffic monitoring to determine if it is feasible
- [ ] set up alert

**Comment by h1z1** [comment]
Fact that the Canadian Government would host this in AWS and not see a conflict is disturbing.

I would think in the interest of privacy as understood by those not in conflict with it's redefinition, more logging is NOT better.

**Comment by obrien-j** [comment]
> I would think in the interest of privacy as understood by those not in conflict with it's redefinition, more logging is NOT better.

Just to clarify, this issue is to gain greater insight into DNS traffic going outbound from the core VPC to ensure visibility in the unlikely chance of a compromise, not related to inbound queries.

**Comment by maxneuvians** [comment]
Same as #337
