### ISSUE TITLE
[Metrics] Write scripts to update sheets

### ISSUE THREAD

**Issue by Stephen-PM** [cds-snc/covid-alert-server#292]
Write scripts to update Google Sheets on a schedule, daily at 8:00 am. 

The intention is to make it easy for HC to generate reports off of the data. These Google Sheets can be used for reporting or to fuel reports using other reporting tools.

**Comment by CalvinRodo** [comment]
Located here: 
https://github.com/cds-snc/covid-alert-server-metrics-extractor

Private Repos: 
https://github.com/cds-snc/covid-alert-server-staging-metrics-extractor
https://github.com/cds-snc/covid-alert-server-prod-metrics-extractor
