### ISSUE TITLE
Refactor Go Unit Tests

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/covid-alert-server#307]
Lots of copy and paste, there is a lot of opportunities to clean this up. 

Risk: the tests work, this would just clean them for more readibilty.

**Comment by c3ho** [comment]
Hi, I'm new to Go, but have written unit tests before in javascript for another open source project. Can I take on this issue?

**Comment by CalvinRodo** [comment]
Hi @c3ho we are always happy to review PR's from outside contributors.

**Comment by CalvinRodo** [comment]
Is being done as Go tests are worked on will close this issue.
