### ISSUE TITLE
Generate metric for time between OTK generation and OTK claim

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-server#308]
This was a request to analyse time to live and time to claim for OTK's as a precursor to further evaluating the expiry duration and whether we could safely reduce the timeout.

Potential enhancement would be to also genetric a metric (new db field) for OTK's that are 'regenerated', which would throw off the eventual metric.

Estimated a day of effort.

This should be done similarly to the metrics for HC.

AC:

- [x]  Collect event data.
- [x]  Create metric endpoint
- [ ]  ~Create a Google Sheet that is updated daily with the metric values.~

**Comment by Stephen-PM** [comment]
Estimated a day of effort.

**Comment by CalvinRodo** [comment]
Extractor work is tracked here https://github.com/cds-snc/covid-alert-server-metrics-extractor/issues/2 

Closed in favour of broken out task as Prod deployment will not happen until Wednesday December 9th.
