### ISSUE TITLE
Automation to reduce support burden on Server Team

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/covid-alert-server#318]
- [x] Self Serve Clearing of DB (not prod)

- [ ] Environment with no caching

Risk: toil reduction, allow the app team to perform tasks themselves.

**Comment by smcmurtry** [comment]
Thanks @CalvinRodo! Those are the main features I want to make manual exposure testing easier.

**Comment by timarney** [comment]
Also the goal is to allow a QA testers to be able to perform these steps.

**Comment by maxneuvians** [comment]
Partially addressed in #332

**Comment by CalvinRodo** [comment]
No longer needed with new QA Tools coming and script for creating cache invalidations.
