### ISSUE TITLE
Endpoint for Clearing Diagnosis Keys in Database

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/covid-alert-server#331]
**PLEASE NOTE:** This would be used in the staging environment only for QA Purposes only

This end point when called with an API Key should trunc the diagnosis_keys table

**Comment by maxneuvians** [comment]
You can add a:

```
if os.Getenv("ENV") == "staging" {
```

like we used here:

https://github.com/cds-snc/covid-alert-server/pull/235/files#diff-0d7a816670026797c98bbe0113a27eee86e6cc27f73f4e1fdd79995503105890R33-R36

**Comment by CalvinRodo** [comment]
That was the plan, I also want to add a check in the prod repo to fail merges if environment is set to anything but production, and possibly an alarm in AWS as well.
