### ISSUE TITLE
Separate alarms per province

### ISSUE THREAD

**Issue by Stephen-PM** [cds-snc/covid-alert-server#336]
We currently have alarms for the overall values. Separating them out by province will allow us to have more refined alarms.

Risk: alerts are not sensitive enough because we are not accounting for the differences between PTs.

AC:
- [ ] Establish baselines for each PT.
- [ ] Configure alarms for each PT.

**Comment by CalvinRodo** [comment]
Would be nice but we haven't had a need for this yet will re-open if the need resurfaces.
