### ISSUE TITLE
Optimizing environments

### ISSUE THREAD

**Issue by Stephen-PM** [cds-snc/covid-alert-server#338]
We are currently running four instances of the COVID Alert server:
- Sandbox
- Staging
- Demo
- Production

They are currently all running the same database, compute, and memory configuration to ensure there is no drift between environments.

AC:

- [x] Reduce the ECS environments for the staging environment
- [x] Reduce the RDS environments for the staging environment
- [x] Verify RDS Environment is db.t3.small for the staging environment
- [x] Reduce the ECS environments for the demo environment.
- [x] Reduce the RDS environments for the demo environment.
- [x] Verify RDS Environment is db.t3.small for the demo environment
- [x] Shut down the Sandbox environment.

**Comment by CalvinRodo** [comment]
@maxneuvians shut down sandbox and archived the associated repository

**Comment by CalvinRodo** [comment]
ECS in staging is scaled down in for vCPU and Mem but desired tasks did not scale down will have to investigate.

**Comment by CalvinRodo** [comment]
RDS Instances should change during next maintenance window: 

Demo: 2020-11-30 Overnight
Staging: 2020-11-25 Overnight 

I'll close this issue when I've verified that the DB instances downgraded successfully.

**Comment by CalvinRodo** [comment]
Only one of the 3 staging databases scaled down, going to manually scale down.

**Comment by CalvinRodo** [comment]
Didn't scale down Production as part of this task. 

Will handle in a separate issue.

**Comment by CalvinRodo** [comment]
Confirmed Demo RDS is scaled down.
