### ISSUE TITLE
Include requestor's IP address in logs

### ISSUE THREAD

**Issue by Stephen-PM** [cds-snc/covid-alert-server#339]
Logging can be improved by adding the requestor’s IP address in the log for the server’s response. This will make it a lot easier to see where bad requests are coming from, without having to combine data from multiple logs. 

Acceptance criteria:
- [ ] whenever a key-claim request fails, the IP is logged with the error message.

**Comment by CalvinRodo** [comment]
Haven't had the need for this yet will re-open if the need occurs.
