### ISSUE TITLE
Metrics - TEK uploads missing from Nov 8

### ISSUE THREAD

**Issue by Stephen-PM** [cds-snc/covid-alert-server#340]
Investigate why the TEK upload data on November 8, where we recorded only 5 first time uploaders (vs the expected ~86). 

AC:
- [ ] Figure what happened
- [ ] Update the spreadsheet to include all the events.
- [ ] Inform Mark that the data is correct

**Comment by CalvinRodo** [comment]
There was a google app script error that occurred, 

This is what I received: 

**Exception: Too many simultaneous invocations: Spreadsheets**

I'm unsure what happened or how to recreate it. 

What I'll do is update our google app script so I'm not the only one being notified. 

I deleted the existing data for the 8th and re-extracted that data.
