### ISSUE TITLE
Document the service continuity requirements

### ISSUE THREAD

**Issue by stephenyates-cds** [cds-snc/covid-alert-server#341]
This is one of the deliverables from the COVID Exposure Notification Service Plan of Action and Milestones.

AC:
- [ ] Draft for Emily and Caitlin to review
- [ ] Final version shared

https://docs.google.com/document/d/12TKC3jJv2c1z2emciHirzcbluHSjC_S9rECtL2E9Ono/edit

**Comment by caitlintuba** [comment]
These requirements should be around recovery time objective (how long can we be offline without a big hubbub) and recovery point objective (how much data can we lose without there being a big impact).

Also could re-look at the severity definitions and defined response and resolution times. These are in the support documentation https://docs.google.com/document/d/1TS5glAwCxyWXD-3yKih3wLzOOs7OS0G24CPBz1SQkfw/edit#bookmark=id.htvmcbz9q6gx

**Comment by CalvinRodo** [comment]
Missing required information from dependent projects

**Comment by CalvinRodo** [comment]
not doing this
