### ISSUE TITLE
Document vulnerability triage process 

### ISSUE THREAD

**Issue by caitlintuba** [cds-snc/covid-alert-server#342]
As part of the system documentation - need to document vulnerability triage process for each team. 
Including what repository private issues will reside in prior to deployment 

https://docs.google.com/document/d/1iP27GXqndny_rbChT9Mk_zt_hfXKjD-vWThYSA305sE/edit?ts=5f6044d7#bookmark=id.z52dhcy8qjh1

**Comment by CalvinRodo** [comment]
Provided a high level overview of the server vuln triage process
