### ISSUE TITLE
Document vulnerability identification

### ISSUE THREAD

**Issue by caitlintuba** [cds-snc/covid-alert-server#343]
As part of the system documentation - need to document all activities related to the identification of vulnerabilities.
https://docs.google.com/document/d/1iP27GXqndny_rbChT9Mk_zt_hfXKjD-vWThYSA305sE/edit?ts=5f6044d7#bookmark=id.1nw0tyfjf3yw

**Comment by CalvinRodo** [comment]
Completed with checks done for Server
