### ISSUE TITLE
Document how we authorize and distribute accounts

### ISSUE THREAD

**Issue by caitlintuba** [cds-snc/covid-alert-server#344]
As part of the system documentation - need to document how we authorize humans and provide them accounts to access COVID Alert. https://docs.google.com/document/d/1lji9tiedOZxSG-NPdAXg7oI_lD-orkZdvwPNjQLcQXs/edit#heading=h.v96wrwh8uf0n

**Comment by CalvinRodo** [comment]
Filled out to the best of my ability. 

Passed on to @maxneuvians to complete the following: 

- Security members
- External security partners
- Emergency members (AWS DDOS)

**Comment by CalvinRodo** [comment]
Information has been added.
