### ISSUE TITLE
Document security monitoring / tooling

### ISSUE THREAD

**Issue by caitlintuba** [cds-snc/covid-alert-server#345]
As part of system documentation - need to document an overview of AWS / Cloud Security monitoring and tooling.  https://docs.google.com/document/d/1lji9tiedOZxSG-NPdAXg7oI_lD-orkZdvwPNjQLcQXs/edit#bookmark=id.bbneo898sf6g

**Comment by CalvinRodo** [comment]
Waiting on @maxneuvians to finish up server work.
