### ISSUE TITLE
Document Development Lifecycle / Release Plan

### ISSUE THREAD

**Issue by caitlintuba** [cds-snc/covid-alert-server#346]
As part of system documentation - need to document the release plan / software development lifecycle.
I pulled from other resources to have <something> but please rewrite / redo / re<something> to a format / content that works for your team moving forward.
https://docs.google.com/document/d/1AeGT_9oGWNzF_J96NWSJNvxq2zLMOGKQKhb1zn6F9F0/edit

**Comment by CalvinRodo** [comment]
Waiting on a response for the following question: [Link to G-Suite Comment](https://docs.google.com/document/d/1AeGT_9oGWNzF_J96NWSJNvxq2zLMOGKQKhb1zn6F9F0/edit?disco=AAAAHUgDVZA) before either continuing or closing this issue.

**Comment by CalvinRodo** [comment]
Waiting on an answer from @caitlintuba before I add more or close out.

**Comment by CalvinRodo** [comment]
I'm pretty sure what Max wrote is sufficient.
