### ISSUE TITLE
Track usage events

### ISSUE THREAD

**Issue by Stephen-PM** [cds-snc/covid-alert-server#348]
Outcome: Securely and anonymously measure the app usage metrics.

How: The app will call a server endpoint when an event occurs. The server will anonymously add the event to an aggregate tally.

AC:
- [ ] Add a new /events end point that will aggregate discreet events into daily data by device type
- [ ] Confirm that requests are coming from the mobile app using DeviceCheck and SafetyNet

**Comment by CalvinRodo** [comment]
closed in favour of #411
