### ISSUE TITLE
Request for OTK Claimed and OTK Unclaimed metrics by the date generated

### ISSUE THREAD

**Issue by Stephen-PM** [cds-snc/covid-alert-server#349]
Mark has requested new feeds for the  OTK Claimed metric and OTKs Unclaimed metric but by date the OTK is generated instead of the date deleted from the DB?

He wants to know: "out of all the OTKs generated on a particular date, how many of them were claimed, and how many were unclaimed. I thought I could just figure this out since OTKs expire after 24 hours, so by subtracting one day I get the OTK expired by date generated. But even if you account for OTKs that are generated on one day and claimed on the next, I’m seeing too big a discrepancy on some days and it is not matching up properly."

AC:

- [ ] Record new event for OTK generated
- [ ] Record new event for OTK claimed
- [ ] Expose the data

**Comment by CalvinRodo** [comment]
Based on metrics coming in on OTK Duration looks like vast majority are claimed within an hour

**Comment by CalvinRodo** [comment]
We've received no follow up on this, and with the new metric OTK Duration this should no longer be needed.
