### ISSUE TITLE
Expose App Metrics

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/covid-alert-server#408]
Create an API Endpoint in Covid Alert Server that allows for someone to call it and recieve the metrics for a specific date. 

## AC 
 - An endpoint that exposes the aggregate metrics collected in #407 
 - The endpoint is able to be passed the date through the URL and this data will be returned as a JSON object containing all the aggregated events logged on that specific date. 
 - The endpoint will be secured so only authenticated individuals can call it.
 - Automated Tests have been written for this endpoint
 - Infrastructure as Code is written for this endpoint 
 - API Documentation has been updated for this new endpoint
 - CI is updated for new service
   - Linting of new source code (see #418)
   - Snyk scanning of new dependencies
   - New Tests are running on PR

**Comment by LeCanardQuoi** [comment]
Could the same solution not provide for sharing at large app adoption rate info important to users wishing to understand the usefulness of their app and how much protection can realistically be expected? I am assuming that this requirement has been fully recognized by now. Building trust with user base is indeed important to increase this user base. There is also here a leadership opportunity to show to all these provincial and regional health bodies an example of how to openly share key performance data. May I suggest that HC (and the canadian advisory council) participate to this github server thread and flag the data that is considered too sensitive and therefore wish to limit access to?

**Comment by CalvinRodo** [comment]
At this time I'm unaware if this data will be shared with the public, all I can say is that we currently have no requirements for  that I am aware of that specify that.

Also this task is purely for tracking development work on this feature in regards to the Covid Alert Server team at CDS, and so HC and the Canadian Advisory Council will not be participating here.

**Comment by LeCanardQuoi** [comment]
> At this time I'm unaware if this data will be shared with the public, all I can say is that we currently have no requirements for that I am aware of that specify that.
> 
> Also this task is purely for tracking development work on this feature in regards to the Covid Alert Server team at CDS, and so HC and the Canadian Advisory Council will not be participating here.

The orginal thread indicated a reauurement for CDS Researchers as well as HC. So it would make sense for HC to partcipate to thread, certainly in the absence of a signed requirement repository. If there is such a repository, it would be most useful to store on this github. If there is no such repository, it must be very challenging to manage the development and maintenance of line undertaking.

**Comment by CalvinRodo** [comment]
So this thread when it mentions folks outside of the server team that's purely for contextual reasons for developers on the server team. 

Non-technical work which includes discussions between CDS and other government entities and stakeholders is not being tracked in this repository, we also currently have no plans to start tracking that work on GitHub.

**Comment by obrien-j** [comment]
@LeCanardQuoi I've enabled Github's 'Discussions' feature on this repo, in a purely experimental state, so apologies if it's not fully baked.

https://github.com/cds-snc/covid-alert-server/discussions

I'd recommend taking some of these more meta-questions over there, to allow the teams to focus on issue delivery in the issues thread. 

Always happy to have input from folks not on the delivery team, just trying to carve out space for each specific thread so that folks can focus when they need to put their heads down.

Cheers.

**Comment by LeCanardQuoi** [comment]
I understand that in an "Agile" development world, traditional requirements statement has been deemphasized but then rely on indepth participation of the "customer" to keep things rolling. So do you not have such an indepth (online during a pandemic) participation of actual core users of the app? Can you not publish/share the current set of requirements of these core users, eithef on the github or elsewhere? Can it not be supplied via email otherwise?

**Comment by obrien-j** [comment]
> I understand that in an "Agile" development world, traditional requirements statement has been deemphasized but then rely on indepth participation of the "customer" to keep things rolling. So do you not have such an indepth (online during a pandemic) participation of actual core users of the app? Can you not publish/share the current set of requirements of these core users, eithef on the github or elsewhere? Can it not be supplied via email otherwise?

Great set of 'meta' questions to pop over into the Discussions page to get us started. 👍

**Comment by CalvinRodo** [comment]
All further Meta Comments on this issue will be moved to the Discussions tab.

**Comment by CalvinRodo** [comment]
CSV ETL is done closing this while we wait for that to be opened.
