### ISSUE TITLE
QR Code - Exposure Event Portal Endpoint

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/covid-alert-server#423]
## Description

We need an endpoint that can be called by the Covid Alert Portal that can be used to POST Exposure Events. 

This Endpoint will sit on the Submission server and will be protected using the same WAF rules as the OTK generation end point and will be authenticated using the same bearer token that is currently used to limit OTK Generation to PTs

## AC

 - Unit Tests of new functionality
 - Updated E2E Ruby Tests
 - Endpoint that takes an exposure event and stores it in the database

**Comment by CalvinRodo** [comment]
@maxneuvians is this completed?

**Comment by maxneuvians** [comment]
Closed in https://github.com/cds-snc/covid-alert-server/pull/438
