### ISSUE TITLE
Add todays date to the region.json file

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/covid-alert-server#439]
In order to provide the app with a well-known date we will add todays date pinned to midnight in epoch time so that the app can attach that to metrics generated on that date.

**Comment by maxneuvians** [comment]
![Screen Shot 2021-02-19 at 12 54 06 PM](https://user-images.githubusercontent.com/867334/108542437-ba946f80-72b1-11eb-9213-99e404333c3e.png)

Might as well just get it out of the response header
